project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "documents/wk6/"

book:
  title: "Markup Languages and Reproducible Programming in Statistics"
  repo-url: https://github.com/mlarpis/markup
  repo-branch: main
  repo-actions: [edit, issue]
  author: 
  - name: Pablo Mosteiro
    orcid: 0000-0001-7231-2773
    email: p.mosteiro@uu.nl
    # affiliations:
    # -name:
  - name: Hanne Oberman
    orcid: 0000-0003-3276-2141
    email: h.i.oberman@uu.nl
    # affiliations: 
    # - name: 
  date: last-modified
  chapters:
    - index.qmd
    - overview.qmd
    - team.qmd
    - deliverables.qmd
    - genai.qmd
    - week 1.qmd
    - week 2.qmd
    - week 3.qmd
    - week 4.qmd
    - week 5.qmd
    - week 6.qmd
    - story.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    toc-depth: 3
    theme: cosmo
