# GenAI rules {.unnumbered}

## Copyright and intellectual property

::: callout-tip
# Do you know your input rights?

The false sense of privacy associated with personal AI use often leads users to share confidential or unauthorized information.
Specifically,

- Do not input course materials, scientific manuscripts or any other work without permission from the owners.
- Avoid using AI tools to process or evaluate each other's work unless you have the author’s consent.
:::

## What about this course?
The materials in this course are generated by M&S teaching staff, who hold the copyright. The intellectual property belongs to Utrecht University.

::: callout-tip
# AI index

The [AI index](https://www.uu.nl/en/organisation/ai-policy/students/ai-index) for this course is C. You **may use GenAI to *prepare* the work you hand in, and to *generate* ideas and content that is part of the work your hand in, for the stages/parts of the assignment stated below**. This includes, but is not limited to, generating text, audio, images, video, and code.

**You may use AI tools to assist you in generating code** that results in reproducible data sets.

**You may NOT generate data sets with GenAI.**
:::

::: {.callout-warning}
- You **may NOT** input staff or student names to generative AI tools.

- You must ensure that the content is not used for further training of the model.
:::

## Our advice

Mastering a new language requires practice, and becoming dependent on genAI will hinder your progress in the long run. One of the essential skills of a developer is to be able to explain and debug their code; blindly relying on genAI will not teach you that. Therefore we advice you to also interact with your instructors, peers and other resources around the web. If you can explain to others what and why you are doing, you have transformed from student to master. 
