# Packages {#sec-wk6}

## Real title: Packages, Code Robustness and Unit Testing

::: callout-tip
## Lecture Week 6

We discussed the flow of creating [`R` packages](https://r-pkgs.org/){target="_blank"} and [`Shiny` apps](https://shiny.posit.co){target="_blank"}. Along the way, we touched upon the importance of version control, testing and documentation. A static version of the Shiny slides can be found [here](slides/shiny/lec-shiny.pdf){target="_blank"}. Our tutorial for R package development can be found [here](documents/wk6/pkg-dev.html){target="_blank"}, and you can see a previous year's recording [here](https://www.dropbox.com/scl/fi/hscfsrh30slk23k7z6d1d/wk6_recording.mp4?rlkey=yhy7wt8ldfmsybbb3000z1hl0&dl=0) (download for the 1h+ recording)
:::

## Exercise 1

Follow the guided tutorial on R package development from [this page](documents/wk6/pkg-dev.html){target="_blank"}.

## Exercise 2

Set up a version controlled workflow to develop either an R package *or* a Shiny app. The topic of this R package or Shiny app may be anything, as long as the finished product is non-trivial. That is, the R package or Shiny app should have clear functionality and contain more than boilerplate code or defaults. 
Make sure to document the development process step-by-step with `git` commits, and make the end-product referencable with a [Zenodo](https://zenodo.org/){target="_blank"} DOI.

The finished end-product of this exercise should be handed in as part of the course [deliverables](deliverables.qmd){target="_blank"}.
